define({

  "yes": "Yes",
  "no": "No",
  "ok": "确定",
  "cancel": "取消",
  "close": "关闭",
  "loading": "载入中",
  "select": "选择",
  "error": "错误",
  "error_network": "网络错误 !",
  "error_network_timeout": "网络超时 !",
  "error_occurred": "发生错误 !",
  "delete": "删除",
  "deleting": "删除中",
  "deleteConfirm": "您确实要删除这条记录吗,此操作无法撤销?",
  "datepicker_format_date": "yy/mm/dd",
  "datepicker_format_time": "HH:mm:ss",
  "datepicker_format_timez": "HH:mm:ss z",
  "datepicker_localization": {
    "currentText": "现在",
    "closeText": "完成",
    "amNames": ["上午", "A"],
    "pmNames": ["下午", "P"],
    "timeFormat": "HH:mm:ss",
    "timeSuffix": "",
    "timeOnlyTitle": "选择时间",
    "timeText": "时间",

    "hourText": "时",
    "minuteText": "分",
    "secondText": "秒",
    "millisecText": "Millisecond",
    "microsecText": "Microsecond",
    "timezoneText": "时区",
    "isRTL": false,
    "prevText": "<",
    "nextText": ">",
    "monthNames": ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
    "monthNamesShort": ["一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "十一", "十二"],
    "dayNames": ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
    "dayNamesShort": ["日", "一", "二", "三", "四", "五", "六"],
    "dayNamesMin": ["日", "一", "二", "三", "四", "五", "六"],
    "weekHeader": "周",
    "dateFormat": "yy/mm/dd",
    "firstDay": 0,
    "showMonthAfterYear": false,
    "yearSuffix": ""
  }

});