define({

  "yes": "Yes",
  "no": "No",
  "ok": "OK",
  "cancel": "Cancel",
  "close": "Close",
  "loading": "Loading",
  "select": "Select",
  "error": "Error",
  "error_network": "Network error !",
  "error_network_timeout": "Network timeout !",
  "error_occurred": "An error occurred !",
  "delete": "Delete",
  "deleting": "Deleting",
  "deleteConfirm": "Do you want to delete the record?",
  "datepicker_format_date": "yy/mm/dd",
  "datepicker_format_time": "HH:mm:ss",
  "datepicker_format_timez": "HH:mm:ss z",
  "datepicker_localization": {
    "currentText": "Now",
    "closeText": "Done",
    "amNames": ["AM", "A"],
    "pmNames": ["PM", "P"],
    "timeFormat": "HH:mm:ss",
    "timeSuffix": "",
    "timeOnlyTitle": "Choose Time",
    "timeText": "Time",

    "hourText": "Hour",
    "minuteText": "Minute",
    "secondText": "Second",
    "millisecText": "Millisecond",
    "microsecText": "Microsecond",
    "timezoneText": "Time Zone",
    "isRTL": false,
    "prevText": "<",
    "nextText": ">",
    "monthNames": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    "monthNamesShort": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    "dayNames": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    "dayNamesShort": ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    "dayNamesMin": ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
    "weekHeader": "Wk",
    "dateFormat": "yy/mm/dd",
    "firstDay": 0,
    "showMonthAfterYear": false,
    "yearSuffix": ""
  }
});